global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  # Elastin Research Project Monitoring
  - job_name: 'elastin-research'
    static_configs:
      - targets: ['elastin-jupyter:8888', 'elastin-gpu:9090']
    metrics_path: '/metrics'
    scheme: 'http'

  # Grant Application Monitoring
  - job_name: 'grantapp-frontend'
    static_configs:
      - targets: ['grantapp-frontend:3000']
    metrics_path: '/metrics'
    scheme: 'http'

  - job_name: 'grantapp-backend'
    static_configs:
      - targets: ['grantapp-backend:4000']
    metrics_path: '/metrics'
    scheme: 'http'

  # Database Monitoring
  - job_name: 'mongodb'
    static_configs:
      - targets: ['mongodb-exporter:9216']
    metrics_path: '/metrics'
    scheme: 'http'

  - job_name: 'redis'
    static_configs:
      - targets: ['redis-exporter:9121']
    metrics_path: '/metrics'
    scheme: 'http'

  # Infrastructure Monitoring
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']
    metrics_path: '/metrics'
    scheme: 'http'

  # Self Monitoring
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
    metrics_path: '/metrics'
    scheme: 'http' 